---
# Credentials for private registry
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-siteminder-registry-key
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
# Secrets for CA Single Sign-On
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-siteminder-{{ .Values.sso.accessGateway.regsecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
type: Opaque
data:
  adminName: {{ .Values.sso.adminUserName }}
  adminPassword: {{ .Values.sso.adminUserPassword }}
---
# Secrets for CA Single Sign-On awsS3 Startup Configuration Repository 
{{ if and .Values.sso.configuration.type (eq .Values.sso.configuration.type "awsS3") }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-siteminder-{{ .Values.sso.configuration.aws.creds }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
type: Opaque
data:
  awskeyid: {{ .Values.sso.configuration.aws.keyId }}
  awssecretaccesskey: {{ .Values.sso.configuration.aws.accessKey }}
{{ end }}
---
# Secrets for CA Single Sign-On awsS3 Runtime Configuration Repository 
{{ if and .Values.sso.runtime.configuration.isEnable (eq .Values.sso.runtime.configuration.isEnable "YES") }}
{{ if and .Values.sso.runtime.configuration.type (eq .Values.sso.runtime.configuration.type "awsS3") }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-siteminder-{{ .Values.sso.runtime.configuration.aws.creds }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
type: Opaque
data:
  runtimeawskeyid: {{ .Values.sso.runtime.configuration.aws.keyId }}
  runtimeawssecretaccesskey: {{ .Values.sso.runtime.configuration.aws.accessKey }}
{{ end }}
{{ end }}
---
# Secrets for CA Single Sign-On GITHUB Startup Configuration Repository 
{{ if and .Values.sso.configuration.type (eq .Values.sso.configuration.type "git") }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-siteminder-{{ .Values.sso.configuration.git.creds }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
type: Opaque
data:
  githubAccessToken: {{ .Values.sso.configuration.git.accessToken }}
{{ end }}
---
# Secrets for CA Single Sign-On GITHUB Runtime Configuration Repository 
{{ if and .Values.sso.runtime.configuration.isEnable (eq .Values.sso.runtime.configuration.isEnable "YES") }}
{{ if and .Values.sso.runtime.configuration.type (eq .Values.sso.runtime.configuration.type "git") }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-siteminder-{{ .Values.sso.runtime.configuration.git.creds }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
type: Opaque
data:
  gitRuntimeAccessToken: {{ .Values.sso.runtime.configuration.git.accessToken }}
{{ end }}
{{ end }}
---
# Secrets for CA Single Sign-On MasterKey Seed
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-siteminder-{{ .Values.masterkey.creds }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
type: Opaque
data:
  masterKeySeed: {{ .Values.masterkey.masterKeySeed  }}

