{{- if .Values.admin.enabled -}}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-siteminder-adminui-ssl-rewrite
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
  annotations:
    nginx.org/ssl-services: "default-https-backend"
    nginx.org/ssl-services: {{ .Release.Name }}-siteminder-admin
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /iam/siteminder/console
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "JSESSIONID"
    nginx.ingress.kubernetes.io/upstream-vhost: {{ .Values.admin.ingress.hostName }}:8443
    nginx.ingress.kubernetes.io/proxy-redirect-from: "https://{{ .Values.admin.ingress.hostName }}:8443"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://{{ .Values.admin.ingress.hostName }}"

spec:
  backend:
    serviceName: default-https-backend
    servicePort: 443
  rules:
  - host: {{ .Values.admin.ingress.hostName }}
    http:
      paths:
        - path: /adminui
          backend:
            serviceName: {{ .Release.Name }}-siteminder-admin
            servicePort: {{ .Values.admin.ingress.servicePort }}
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-siteminder-adminui-ovm-ssl
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
  annotations:
    nginx.org/ssl-services: "default-https-backend"
    nginx.org/ssl-services: {{ .Release.Name }}-siteminder-ovm-admin
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  backend:
    serviceName: default-https-backend
    servicePort: 443
  rules:
  - host: {{ .Values.admin.ingress.hostName }}
    http:
      paths:
        - path: /sitemindermonitor
          backend:
            serviceName: {{ .Release.Name }}-siteminder-ovm-admin
            servicePort: {{ .Values.admin.ingress.servicePort }}
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-siteminder-ssl
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
  annotations:
    nginx.org/ssl-services: "default-https-backend"
    nginx.org/ssl-services: {{ .Release.Name }}-siteminder-admin
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "JSESSIONID"
    nginx.ingress.kubernetes.io/upstream-vhost: {{ .Values.admin.ingress.hostName }}:8443
    nginx.ingress.kubernetes.io/proxy-redirect-from: "https://{{ .Values.admin.ingress.hostName }}:8443"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://{{ .Values.admin.ingress.hostName }}"
spec:
  backend:
    serviceName: default-https-backend
    servicePort: 443
  rules:
  - host: {{ .Values.admin.ingress.hostName }}
    http:
      paths:
        - path: /iam/
          backend:
            serviceName: {{ .Release.Name }}-siteminder-admin
            servicePort: {{ .Values.admin.ingress.servicePort }}
        - path: /castylesr5.1.1/
          backend:
            serviceName: {{ .Release.Name }}-siteminder-admin
            servicePort: {{ .Values.admin.ingress.servicePort }}
  tls:
  - hosts:
    - {{ .Values.admin.ingress.hostName }} 
    secretName: {{ .Release.Name }}-siteminder-{{ .Values.admin.ingress.tlsSecret }}  
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}-siteminder-rest-endpoint
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
  annotations:
    nginx.org/ssl-services: "default-https-backend"
    nginx.org/ssl-services: {{ .Release.Name }}-siteminder-admin
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "JSESSIONID"
    nginx.ingress.kubernetes.io/upstream-vhost: {{ .Values.admin.ingress.hostName }}:8443
    nginx.ingress.kubernetes.io/proxy-redirect-from: "https://{{ .Values.admin.ingress.hostName }}:8443"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://{{ .Values.admin.ingress.hostName }}"
spec:
  backend:
    serviceName: default-https-backend
    servicePort: 443
  rules:
  - host: {{ .Values.admin.ingress.hostName }}
    http:
      paths:
        - path: /ca/api/sso/services/
          backend:
            serviceName: {{ .Release.Name }}-siteminder-admin
            servicePort: {{ .Values.admin.ingress.servicePort }}
{{- end }}
