{{- if .Values.admin.enabled -}}
apiVersion: v1
data:
  tls.crt: {{ .Values.admin.ingress.tlsCrt }}
  tls.key: {{ .Values.admin.ingress.tlsKey }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-siteminder-{{ .Values.admin.ingress.tlsSecret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
